// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAktk10Zpp3BIb1MKnejNKaIVc69koCFkY',
    appId: '1:1019590537708:web:3b71774c5ec25e9539d0c9',
    messagingSenderId: '1019590537708',
    projectId: 'evide-ai-2b3d2',
    authDomain: 'evide-ai-2b3d2.firebaseapp.com',
    storageBucket: 'evide-ai-2b3d2.firebasestorage.app',
    measurementId: 'G-KHXQ5CDD4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBURYxZ9OO2ashOf4vTUml44boDKSLM6fg',
    appId: '1:1019590537708:android:61fa1a1c4652954839d0c9',
    messagingSenderId: '1019590537708',
    projectId: 'evide-ai-2b3d2',
    storageBucket: 'evide-ai-2b3d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8uUDH72djE-0tM1tgT_o0aroZCo3RZzw',
    appId: '1:1019590537708:ios:71e8803b3f17326a39d0c9',
    messagingSenderId: '1019590537708',
    projectId: 'evide-ai-2b3d2',
    storageBucket: 'evide-ai-2b3d2.firebasestorage.app',
    iosBundleId: 'com.evde.evideAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8uUDH72djE-0tM1tgT_o0aroZCo3RZzw',
    appId: '1:1019590537708:ios:e914410b4ce0b4e039d0c9',
    messagingSenderId: '1019590537708',
    projectId: 'evide-ai-2b3d2',
    storageBucket: 'evide-ai-2b3d2.firebasestorage.app',
    iosBundleId: 'com.example.evideUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAktk10Zpp3BIb1MKnejNKaIVc69koCFkY',
    appId: '1:1019590537708:web:483c5c3657eda40c39d0c9',
    messagingSenderId: '1019590537708',
    projectId: 'evide-ai-2b3d2',
    authDomain: 'evide-ai-2b3d2.firebaseapp.com',
    storageBucket: 'evide-ai-2b3d2.firebasestorage.app',
    measurementId: 'G-4YLX6Q7K4Y',
  );

}